[tool.isort]
known_first_party = ["script"]
profile = "black"
skip_glob = ".venv"

[tool.black]
extend-exclude = '''
(
  .venv
)
'''
target-version = ["py311"]

[tool.pyright]
include = [
  "..",
]
ignore = [
    "../documentation",
    "../development/.venv",
]
