[tool.poetry]
name = "cal-aws-modules"
version = "0.1.0"
description = "CalSev AWs Modules"
authors = ["CalSev Team"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"

[tool.poetry.group.test.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
known_first_party = ["script"]
profile = "black"
skip_glob = ".venv"

[tool.black]
extend-exclude = '''
(
  .venv
)
'''
target-version = ["py311"]

[tool.pyright]
include = [
  "..",
]
ignore = [
    "../documentation",
    "../development/.venv",
]
