FROM ${ecr_repo_url}:${ecr_repo_tag}

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive \
    TERM=xterm-256color \
    TZ=Etc/UTC \
    pkg='apt-get install -qqy --no-install-recommends'

# Upgrade because openvpn-as is not updated often and will have vulnerabilties
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    apt-get -qq update && \
    apt-get -yqq upgrade && \
    $pkg curl less make python-is-python3 python3-pip python3-venv skopeo unzip && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o 'awscliv2.zip' && \
    unzip -q awscliv2.zip && \
    rm awscliv2.zip && \
    aws/install && \
    rm -r aws && \
    apt-get remove -qqy curl unzip && \
    apt-get autoremove -qqy && \
    apt-get clean -qqy && \
    rm -rf /var/lib/apt/lists/*

# Copy factory config into read-only location
RUN mkdir -p /var/opt/openvpn_as && \
    cp -a /usr/local/openvpn_as/* /var/opt/openvpn_as/

COPY entry_point.sh /entry_point.sh
